name: gabolp
description: ColecciÃ³n vinilos
publish_to: "none"

version: 1.0.3+4

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  path: ^1.9.0
  image_picker: ^1.1.2
  http: ^1.2.2
  path_provider: ^2.1.4
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1

flutter:
  uses-material-design: true
  assets:
    - assets/splash/splash.png

flutter_native_splash:
  color: "#121212"
  image: assets/splash/splash.png
  android: true